export interface Project {
  id: number;
  imagePath?: string | null;
  createdAt: string;
  updatedAt?: string | null;
  isUsed?: boolean | null;
  createdBy?: string | null;
  projectName: string;
  location: string;
  completionYear?: string | null;
  belowFloors?: number | null;
  aboveFloors?: number | null;
  buildingHeight: number;
  podiumHeight?: number | null;
  perimeterRatio?: number | null;
  shaftBelowFloors?: number | null;
  shaftAboveFloors?: number | null;
  shaftAdditionalAboveFloors?: number | null;
  evacuationZoneCount?: number | null;
  lobbyHeight?: number | null;
  elevatorHallPartition?: boolean | null;
  lobbyAccessFloor?: boolean | null;
  elevatorHallPartitionStandard?: boolean | null;
  balcony?: boolean | null;
  observationFloor?: boolean | null;
  rooftopGarden?: boolean | null;
  zoningType?: string | null;
  skyLobby?: boolean | null;
  shuttleElevator?: boolean | null;
  hasPodium?: boolean | null;
  buildingGeneralEtcChecked?: boolean | null;
  buildingGeneralEtcInput?: string | null;
  buildingMassEtcChecked?: boolean | null;
  buildingMassEtcInput?: string | null;
  firstStairShaftFloors?: number | null;
  secondStairShaftFloors?: number | null;
  thirdStairShaftFloors?: number | null;
  fourthStairShaftFloors?: number | null;
  fifthStairShaftFloors?: number | null;
  buildingGeneralPlanResidentialGeneral?: boolean | null;
  buildingGeneralPlanResidentialMixed?: boolean | null;
  buildingGeneralPlanOffice?: boolean | null;
  buildingGeneralPlanHotel?: boolean | null;
  buildingGeneralPlanComplex?: boolean | null;
  buildingGeneralPlanRetail?: boolean | null;
  buildingGeneralPlanCultural?: boolean | null;
  buildingGeneralPlanNeighborhood?: boolean | null;
  buildingMassPlanResidential?: boolean | null;
  buildingMassPlanOffice?: boolean | null;
  buildingMassPlanNeighborhood?: boolean | null;
  buildingMassPlanCultural?: boolean | null;
  isEvaluationApplied?: boolean | null;
  isEvaluationDone?: boolean | null;
  imageUrl?: string | StaticImageData | null;
  reportUrl?: string | null;
}
